[[CURRENCIES]]
code="DOGE"
issuer="GCAJTW2R7IUNXD2WS2C757XQY7DCVOIZAI5JNZAQL7SYL57P72WX4Y2I"
name="Wang Xusheng"
desc="This is a test token created on Pi Testnet for learning and demonstration."
image="https://DOGE188DOGE.github.io/DOGE.png"
